'use strict';

const uint=/^int(?:\(\d+\))? unsigned$/, date=/^datetime(?:\(0\))?$/;
const text=(size,ascii=false)=>({type:new RegExp('^varchar\\('+size+'\\)$'),ascii});
const char=size=>({type:new RegExp('^char\\('+size+'\\)$'),ascii:true});
const col=(name,type,extra={})=>({name,type:typeof type==='object'&&!(type instanceof RegExp)?type.type:type,...(typeof type==='object'&&!(type instanceof RegExp)?type:{}),...extra});
const definitions=[
 {name:'cl_campaigns',columns:[col('id',uint,{auto:true}),col('title',text(120)),col('text',/^text$/),col('created_by',uint),col('client_key',char(32)),col('request_hash',char(64)),col('audience_hash',char(64)),col('notice_version',text(40,true)),col('state',text(16,true)),col('created_at',date)],indexes:[['PRIMARY',['id'],true],['cl_campaign_request',['created_by','client_key'],true]],keys:[['created_by','cl_users','id']],
 statement:"CREATE TABLE IF NOT EXISTS cl_campaigns (id INT UNSIGNED NOT NULL AUTO_INCREMENT, title VARCHAR(120) NOT NULL, text TEXT NOT NULL, created_by INT UNSIGNED NOT NULL, client_key CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, audience_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, notice_version VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id), UNIQUE KEY cl_campaign_request(created_by,client_key), FOREIGN KEY(created_by) REFERENCES cl_users(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"},
 {name:'cl_campaign_recipients',columns:[col('campaign_id',uint),col('account_id',uint),col('consent_version',uint),col('state',text(16,true)),col('delivered_at',date,{nullable:true}),col('read_at',date,{nullable:true})],indexes:[['PRIMARY',['campaign_id','account_id'],true],['cl_campaign_queue',['campaign_id','state','account_id'],false],['cl_campaign_inbox',['account_id','state','campaign_id'],false]],keys:[['campaign_id','cl_campaigns','id'],['account_id','cl_portal_accounts','id']],
 statement:"CREATE TABLE IF NOT EXISTS cl_campaign_recipients (campaign_id INT UNSIGNED NOT NULL, account_id INT UNSIGNED NOT NULL, consent_version INT UNSIGNED NOT NULL, state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, delivered_at DATETIME NULL, read_at DATETIME NULL, PRIMARY KEY(campaign_id,account_id), INDEX cl_campaign_queue(campaign_id,state,account_id), INDEX cl_campaign_inbox(account_id,state,campaign_id), FOREIGN KEY(campaign_id) REFERENCES cl_campaigns(id) ON DELETE RESTRICT ON UPDATE RESTRICT, FOREIGN KEY(account_id) REFERENCES cl_portal_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"},
 {name:'cl_campaign_batches',columns:[col('campaign_id',uint),col('client_key',char(32)),col('delivered',uint),col('skipped',uint),col('remaining',uint),col('created_at',date)],indexes:[['PRIMARY',['campaign_id','client_key'],true]],keys:[['campaign_id','cl_campaigns','id']],
 statement:"CREATE TABLE IF NOT EXISTS cl_campaign_batches (campaign_id INT UNSIGNED NOT NULL, client_key CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, delivered INT UNSIGNED NOT NULL, skipped INT UNSIGNED NOT NULL, remaining INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(campaign_id,client_key), FOREIGN KEY(campaign_id) REFERENCES cl_campaigns(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"}
];
async function verifyCampaignSchema(c){
 for(const d of definitions){
  const [cols]=await c.query('SHOW FULL COLUMNS FROM '+d.name);
  if(cols.length!==d.columns.length||d.columns.some(x=>!cols.some(r=>r.Field===x.name&&x.type.test(r.Type.toLowerCase())&&r.Null===(x.nullable?'YES':'NO')&&r.Default===null&&r.Extra===(x.auto?'auto_increment':'')&&(!x.ascii||r.Collation==='ascii_bin'))))throw Error('Colunas de campanhas incompativeis.');
  const [idx]=await c.query('SHOW INDEX FROM '+d.name);
  const matches=([name,fields,unique])=>{const rows=idx.filter(r=>r.Key_name===name).sort((a,b)=>Number(a.Seq_in_index)-Number(b.Seq_in_index));return rows.length===fields.length&&rows.every((r,i)=>r.Column_name===fields[i]&&Number(r.Seq_in_index)===i+1&&Number(r.Non_unique)===(unique?0:1)&&r.Sub_part===null);};
  if(d.indexes.some(x=>!matches(x))||idx.some(r=>Number(r.Non_unique)===0&&!d.indexes.some(x=>x[0]===r.Key_name&&x[2])))throw Error('Indices de campanhas incompativeis.');
  const [table]=await c.execute('SELECT ENGINE AS engine, TABLE_COLLATION AS tableCollation FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?',[d.name]);
  if(table.length!==1||table[0].engine?.toLowerCase()!=='innodb'||table[0].tableCollation!=='utf8mb4_unicode_ci')throw Error('Engine de campanhas incompativel.');
  const [keys]=await c.execute("SELECT k.COLUMN_NAME AS columnName, k.REFERENCED_TABLE_NAME AS referencedTable, k.REFERENCED_COLUMN_NAME AS referencedColumn, (k.REFERENCED_TABLE_SCHEMA = DATABASE()) AS localSchema, r.DELETE_RULE AS deleteRule, r.UPDATE_RULE AS updateRule FROM information_schema.KEY_COLUMN_USAGE k JOIN information_schema.REFERENTIAL_CONSTRAINTS r ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME AND r.TABLE_NAME=k.TABLE_NAME WHERE k.TABLE_SCHEMA=DATABASE() AND k.TABLE_NAME=? AND k.REFERENCED_TABLE_NAME IS NOT NULL",[d.name]);
  if(keys.length!==d.keys.length||d.keys.some(([col,tab,ref])=>!keys.some(k=>k.columnName===col&&k.referencedTable===tab&&k.referencedColumn===ref&&Number(k.localSchema)===1&&k.deleteRule==='RESTRICT'&&k.updateRule==='RESTRICT')))throw Error('Vinculo de campanhas incompativel.');
 }
}
module.exports={definitions,statements:definitions.map(d=>d.statement),verifyCampaignSchema};
