'use strict';
const statement="CREATE TABLE IF NOT EXISTS cl_portal_subscription_events (account_id INT UNSIGNED NOT NULL, version INT UNSIGNED NOT NULL, subscribed TINYINT NOT NULL, notice_version VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, client_key CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (account_id, version), UNIQUE KEY cl_subscription_request (account_id, client_key), INDEX cl_subscription_created (account_id, created_at), FOREIGN KEY (account_id) REFERENCES cl_portal_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
async function verifySubscriptionSchema(c){
 const [columns]=await c.query('SHOW FULL COLUMNS FROM cl_portal_subscription_events');
 const expected=[['account_id',/^int(?:\(\d+\))? unsigned$/],['version',/^int(?:\(\d+\))? unsigned$/],['subscribed',/^tinyint(?:\(\d+\))?$/],['notice_version',/^varchar\(40\)$/],['client_key',/^char\(32\)$/],['request_hash',/^char\(64\)$/],['created_at',/^datetime(?:\(0\))?$/]];
 if(columns.length!==expected.length||expected.some(([name,type])=>!columns.some(r=>r.Field===name&&type.test(r.Type.toLowerCase())&&r.Null==='NO'&&r.Default===null&&!r.Extra&&( !['notice_version','client_key','request_hash'].includes(name)||r.Collation==='ascii_bin'))))throw Error('Estrutura de inscricoes incompativel.');
 const [indexes]=await c.query('SHOW INDEX FROM cl_portal_subscription_events');
 const match=(name,fields,unique)=>{const rows=indexes.filter(x=>x.Key_name===name).sort((a,b)=>Number(a.Seq_in_index)-Number(b.Seq_in_index));return rows.length===fields.length&&rows.every((r,i)=>r.Column_name===fields[i]&&Number(r.Seq_in_index)===i+1&&Number(r.Non_unique)===(unique?0:1)&&r.Sub_part===null);};
 if(!match('PRIMARY',['account_id','version'],true)||!match('cl_subscription_request',['account_id','client_key'],true)||!match('cl_subscription_created',['account_id','created_at'],false)||indexes.some(r=>Number(r.Non_unique)===0&&!['PRIMARY','cl_subscription_request'].includes(r.Key_name)))throw Error('Indices de inscricoes incompativeis.');
 const [table]=await c.execute("SELECT ENGINE AS engine, TABLE_COLLATION AS tableCollation FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cl_portal_subscription_events'");
 if(table.length!==1||table[0].engine?.toLowerCase()!=='innodb'||table[0].tableCollation!=='utf8mb4_unicode_ci')throw Error('Engine de inscricoes incompativel.');
 const [keys]=await c.execute("SELECT k.COLUMN_NAME AS columnName, k.REFERENCED_TABLE_NAME AS referencedTable, k.REFERENCED_COLUMN_NAME AS referencedColumn, (k.REFERENCED_TABLE_SCHEMA = DATABASE()) AS localSchema, r.DELETE_RULE AS deleteRule, r.UPDATE_RULE AS updateRule FROM information_schema.KEY_COLUMN_USAGE k JOIN information_schema.REFERENTIAL_CONSTRAINTS r ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME AND r.TABLE_NAME=k.TABLE_NAME WHERE k.TABLE_SCHEMA=DATABASE() AND k.TABLE_NAME='cl_portal_subscription_events' AND k.REFERENCED_TABLE_NAME IS NOT NULL");
 if(keys.length!==1||keys[0].columnName!=='account_id'||keys[0].referencedTable!=='cl_portal_accounts'||keys[0].referencedColumn!=='id'||Number(keys[0].localSchema)!==1||keys[0].deleteRule!=='RESTRICT'||keys[0].updateRule!=='RESTRICT')throw Error('Vinculo de inscricoes incompativel.');
}
module.exports={statement,verifySubscriptionSchema};
